graph LR
      A[Windows .NET Core MVC<br>Windows .NET Core MVC框架] --> MW[Middleware<br>中間件]
    MW --> B[Web API<br>網絡API]
    MW --> C[Razor Pages<br>Razor頁面]
    C --> CP[Partial Views<br>部分視圖]
    B --> D[RESTful API<br>RESTful API接口]
    A --> E[Dependency Injection<br>依賴注入]
    E --> MW
    A --> VM[View Model<br>視圖模型]
    VM --> C
    VM --> F[Front-end<br>前端]
    F --> G[Vue.js<br>Vue.js框架]
    F --> H[JavaScript<br>JavaScript腳本語言]
    F --> I[HTML<br>HTML標記語言]
    F --> CSS[CSS<br>層疊樣式表]
    CSS --> BS[Bootstrap 5<br>Bootstrap 5框架]
    G --> J[Axios<br>Axios HTTP客戶端]
    H --> K[jQuery<br>jQuery庫]
    H --> L[AJAX<br>AJAX技術]
    H --> M[Chart.js<br>Chart.js圖表庫]
    A --> N[Real-time Communication<br>實時通訊]
    N --> O[SignalR<br>SignalR庫]
    O --> P[WebSocket<br>WebSocket協議]
    A --> Q[Data Access<br>數據訪問]
    Q --> R[Entity Framework Core<br>Entity Framework Core ORM]
    R --> S[EF Core Power Tools<br>EF Core Power Tools]
    A --> T[Authentication & Security<br>認證和安全]
    T --> U[JWT<br>JWT令牌]
    T --> V[Salt<br>加鹽技術]
    T --> MW
    A --> W[External Services<br>外部服務]
    W --> X[Google API<br>Google API]
    W --> Y[Azure<br>Azure雲平台]
    A --> Z[Version Control<br>版本控制]
    Z --> AA[GitHub<br>GitHub代碼托管]
    AA --> AB[SourceTree<br>SourceTree客戶端]
    A --> AC[Data Transfer<br>數據傳輸]
    AC --> AD[DTO<br>數據傳輸對象]
    Q --> VM
    AC --> VM
    Q --> RDB[Relational Database<br>關聯式資料庫]
    RDB --> ASQL[Azure SQL<br>Azure SQL數據庫]
    Y --> ASQL
    W --> BN[NewebPay<br>藍新金流]
    BN --> D
