// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using HaveFun.Models;

namespace HaveFun.Models;

public partial class NorthwindContext : DbContext
{
		public NorthwindContext(DbContextOptions<NorthwindContext> options)
			: base(options)
		{
		}
	
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		if (!optionsBuilder.IsConfigured)
		{
			IConfiguration Config=new ConfigurationBuilder()
				.SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
				.AddJsonFile("appsettings.json")
				.Build();
			optionsBuilder.UseSqlServer(Config.GetConnectionString("Northwind"));
		}
	}

public DbSet<HaveFun.Models.MemberProfile> MemberProfile { get; set; } = default!;
}